### ISSUE TITLE
Basic Language Principles

### ISSUE THREAD

**Issue by nvaytet** [ess-dmsc-dram/python-course-ikon#1]
Create a notebook for module titled "Basic Language Principles"

**Comment by mads-bertelsen** [comment]
**Quick review of this notebook**

I think there should be some introduction before showing the code. Some welcome message.

Blocks already executed when I opened it, so the first exercise where the student have to guess the code outcome makes no sense. Clear the notebook of output before uploading.

“plot function has many options “ -> “the plot function has many options”

“when cursor is pointing on function” -> “when the cursor is pointing on the function”

Could not make Shift+tab+tab to work in Exercise (2)

Three of the bitwise operators operate “in” int instead of “on” int in the operator table.

No block with “YOUR CODE HERE” for exercise 4.

Extra block at the end.

Should explain comments too.

Perhaps it should also introduce += -= *= and /=.

**Comment by wpotrzebowski** [comment]
All the issues have been addressed now and solution notebook's been created
